# Generated by Django 4.0.10 on 2024-01-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_component_delete_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('datasheet', models.BinaryField(null=True)),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.component')),
            ],
            options={
                'db_table': 'Manufacturers',
                'ordering': ['name'],
            },
        ),
    ]
