# Generated by Django 4.0.10 on 2024-01-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('aqtech_part_number', models.CharField(max_length=100)),
                ('foot_print', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Components',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
