# Generated by Django 4.0.10 on 2024-01-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_component_options_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='component_id',
            new_name='component',
        ),
    ]
