# Generated by Django 4.0.10 on 2024-01-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_rename_component_id_manufacturer_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
